apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: weather-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
        - name: weather-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-backend-secret
                  key: OPENWEATHER_API_KEY