replicaCount: 1

namespace: prod

image:
  repository: harirs/weather-frontend
  tag: prod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

container:
  port: 5001

env:
  BACKEND_URL: "http://weather-backend:5000"