apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-backend-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sagiv-Ha/weather-helm-charts.git
    targetRevision: dev
    path: charts/weather-backend
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=truekub