replicaCount: 2

namespace: prod

image:
  repository: harirs/weather-backend
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

container:
  port: 5000

env:
  OPENWEATHER_API_KEY: ""